// -*- C++ -*-
//
// generated by wxGlade 1.0.5 on Thu Feb  8 21:30:53 2024
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef CALCULATORFRAME_H
#define CALCULATORFRAME_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
#include <wx/statline.h>
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class CalculatorFrame: public wxFrame {
public:
    // begin wxGlade: CalculatorFrame::ids
    // end wxGlade

    CalculatorFrame(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:

protected:
    // begin wxGlade: CalculatorFrame::attributes
    wxMenuBar* Calculator_menubar;
    wxStaticText* label_output;
    wxGridSizer* sizer_4;
    wxButton* button_num_7;
    wxButton* button_num_8;
    wxButton* button_num_9;
    wxButton* button_div;
    wxButton* button_num_4;
    wxButton* button_num_5;
    wxButton* button_num_6;
    wxButton* button_mul;
    wxButton* button_num_1;
    wxButton* button_num_2;
    wxButton* button_num_3;
    wxButton* button_sub;
    wxButton* button_comma;
    wxButton* button_num_0;
    wxButton* button_eval;
    wxButton* button_add;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnViewSimple(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnViewAdvanced(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnViewProgrammer(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnDarkModeChange(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnDebugModeChange(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnVersion(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnButtonPressed(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // CALCULATORFRAME_H
