// -*- C++ -*-
//
// generated by wxGlade 1.0.5 on Wed Feb 14 09:49:18 2024
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef CALCULATORFRAME_H
#define CALCULATORFRAME_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class CalculatorFrame: public wxFrame {
public:
    // begin wxGlade: CalculatorFrame::ids
    // end wxGlade

    CalculatorFrame(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:

protected:
    // begin wxGlade: CalculatorFrame::attributes
    wxMenuBar* Calculator_menubar;
    wxStaticText* label_eval;
    wxStaticText* label_symbol;
    wxStaticText* label_input;
    wxRadioButton* radio_btn_base64;
    wxButton* button_base64;
    wxRadioButton* radio_btn_base16;
    wxButton* button_base16;
    wxRadioButton* radio_btn_base10;
    wxButton* button_base10;
    wxRadioButton* radio_btn_base2;
    wxButton* button_base2;
    wxButton* button_num_a;
    wxButton* button_delete;
    wxButton* button_clear;
    wxButton* button_copy;
    wxButton* button_num_b;
    wxButton* button_symbol_bracket_open;
    wxButton* button_symbol_bracket_close;
    wxButton* button_symbol_pow;
    wxButton* button_symbol_sqrt;
    wxButton* button_factorial;
    wxButton* button_num_c;
    wxButton* button_num_7;
    wxButton* button_num_8;
    wxButton* button_num_9;
    wxButton* button_div;
    wxButton* button_negate;
    wxButton* button_num_d;
    wxButton* button_num_4;
    wxButton* button_num_5;
    wxButton* button_num_6;
    wxButton* button_mul;
    wxButton* button_reciprocal;
    wxButton* button_num_e;
    wxButton* button_num_1;
    wxButton* button_num_2;
    wxButton* button_num_3;
    wxButton* button_sub;
    wxButton* button_pi;
    wxButton* button_num_f;
    wxButton* button_comma;
    wxButton* button_num_0;
    wxButton* button_eval;
    wxButton* button_add;
    wxButton* button_percent;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnViewSelection(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnDarkModeChange(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnDebugModeChange(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnVersion(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBaseSelection(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBaseCopy(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnButtonPressed(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // CALCULATORFRAME_H
